### PR TITLE
Integrated Calendar Component

### PR DESCRIPTION
**Pull request by shinjam3**
Note: this was branched off Lin's `multiple-boards` branch, so some of the file changes are from the `multiple-boards` branch

New features and/or changes:
- "Calendar" tab on the navigation bar takes user to the calendar page
- "Dashboard" tab on the navigation bar takes users to the current board page
- The `Calendar` component gets the current board information from the user context and places the cards in calendar cells based on their deadlines
- Note: if a card does not have a deadline, then the card will not show up in the calendar
- Note: `Calendar` component does not update the database after a drag and drop but I am working on that in this same branch

### CODE REVIEW

**Comment by shinjam3** [comment]
The reason why the `Calendar `component was not showing the test `Card` on Monday's stand-up was because the deadline of the card was Feb. 15, while the calendar month was set to March (the `Calendar` component creates a calendar for the month of the current day). The component seems to be receiving the user context data fine, but it only shows the current month

**Review by dproc96 — APPROVED** [review]
This looks good to go

**Comment by shinjam3** [comment]
New changes:
- the `Calendar` component will fetch the current Board information from the DB, when mounting
- an array of all cards in the current board will be made, and the calendar cells will be populated with existing cards
- dragging and dropping a `Card` to a new calendar day will set the `Card`'s "deadline" as the new calendar day

**Review by dproc96 — APPROVED** [review]
This PR looks good to go, I noticed an issue while testing but opened up a new ticket for it because I think it's unrelated

**Pull request merged**
