### PR TITLE
Broken routes fixed and persistent user added.

### PR DESCRIPTION
**Pull request by moods-72**
The socket code is commented out in the Board.js component to verify the persistent user code.  The socket issues on page refreshes is still being worked on.

### CODE REVIEW

**Comment by dproc96** [comment]
Hey Carl, just to clarify this PR is still in progress correct?

**Comment by moods-72** [comment]
Yes, the socket issue is still being worked on.  The PR works fine otherwise.

**Review by dproc96 — APPROVED** [review]
Looks good, nice work on this

**Comment by moods-72** [comment]
Thanks Dan.

**Pull request merged**
